# Generated by Django 2.1.7 on 2019-03-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_is_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_like',
            new_name='is_saved',
        ),
    ]
