# Generated by Django 2.1.7 on 2019-03-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
